services:
  strapi:
    build:
      context: .
      dockerfile: dockerfile
    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
      # Puedes definir otras variables según tu configuración de Strapi
      # APP_KEYS: "your_app_keys"
      # API_TOKEN_SALT: "your_api_token_salt"
      # ADMIN_JWT_SECRET: "your_admin_jwt_secret"
    volumes:
      - strapi_data:/app/back/.tmp
    restart: unless-stopped

volumes:
  strapi_data:
