services:
  strapi:
    build:
      context: .
    container_name: laba-kudeatu
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
    volumes:
      - /var/fosil/laba/kudeatu/back/.tmp:/app/back/.tmp
    restart: unless-stopped

volumes:
  strapi_data:
