services:
  strapi:
    build:
      context: .
      dockerfile: dockerfile
    container_name: strapi
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
    volumes:
      - strapi_data:/app/back/.tmp
    restart: unless-stopped

volumes:
  strapi_data:
