packages:
  - back
  - e2e
  - front

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - cypress
  - esbuild
  - sharp

patchedDependencies:
  strapi-plugin-webp-converter: patches/strapi-plugin-webp-converter.patch
