export type AlergenoIdentifikadorea =
  | 'apioa'
  | 'arraina'
  | 'arrautzak'
  | 'esnekiak'
  | 'fruituLehorrak'
  | 'glutena'
  | 'kakahueteak'
  | 'krustazeoak'
  | 'lupinuak'
  | 'moluskuak'
  | 'sesamoa'
  | 'soja'
  | 'sulfitoak'
  | 'ziapea';
